######################################################################
#
# File name : tb_top_ddr3_hdmi_wave.do
# Created on: Thu Oct 11 09:02:35 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
